version: '3.8'

services:
  api:
    build: .
    container_name: meals-api
    ports:
      - "8000:8000"
    volumes:
      # Для разработки - код монтируется с хоста
      - ./:/app
      # Для продакшена - только папка с БД
      - ./data:/app/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

